version: '3.1'

services:
    database:
        image: mysql:5.7.23
        container_name: database
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        expose:
            - 3306
        ports:
            - 3306:3306
        environment:
            - MYSQL_USER=developer
            - MYSQL_PASSWORD=my-secret-password
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=facturacion-electronica

    proxy:
        image: nginx:1.15
        container_name: proxy
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 9000:9000
        expose:
            - 9000

    session:
        image: redis:4
        container_name: session
        restart: always
        ports:
            - 6379:6379
        expose:
            - 6379

    webapp:
        image: facturacion-electronica:latest
        container_name: webapp
        restart: always
        env_file:
            - server/.env
        ports:
            - 4000:4000
        depends_on:
            - session
            - database